id: I6CEB68BC
ocr_import_info:
  timestamp: '2023-06-28T04:19:28.265168+00:00'
  batch_id: batch-4c79
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 04:38:07.978531+00:00
last_modified: 2023-06-28 04:38:07.978537+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5817
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5817
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུས་མཐའ་རྣམ་འབྱེད་དང་ཆོས་ཉིད་རྣམ་འབྱེད་གཉིས་ཀྱི་འགྲེལ་པ།
  languages:
  - bo
  author: སློབ་དཔོན་དབྱིག་གཉེན།
statistics:
  ocr_word_mean_confidence_index: 0.9994200442010926
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG5839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5839
      total_pages: 300
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5839.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9994200442010926
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
